### ISSUE TITLE
No Captcha ?

### ISSUE THREAD

**Issue by mats852** [gidlov/pico-contact#2]
Hi !

I love using your plugin. Let me thank you first.

Is there a way to add a captcha ? Google's reCaptcha needs a PHP code inserted, which is not possible in the Markdown file.

Any idea ?

**Comment by gidlov** [comment]
Hey.
Excuse the late reply but I've been away a bit. 

I have now added captcha to the class but chose to use gregwar/captcha instead of Google. 

Hope you find use of it henceforth. :)
