### ISSUE TITLE
placeholder="" replaced by pico

### ISSUE THREAD

**Issue by christheyounger** [gidlov/pico-contact#3]
Hi. I've created the markdown file contact.md as specified, but pico is replacing the placeholder="blah" with ="blah". The text 'placeholder' is being replaced with nothing.

**Comment by gidlov** [comment]
Hi Chris
Do you have correct name attribute in your html? Have you looked at the
$_POST variable when you submit the form?

Sorry for short answer (mobile reply)

Have a nice day. ☺

/Klas
Den 4 aug 2015 05:47 skrev "Chris" notifications@github.com:

**Comment by christheyounger** [comment]
I copied the example as is.

```
<input id="captcha" name="captcha" type="text" class="form-control" placeholder="Write the characters in the picture">
```

becomes

```
<input id="captcha" name="captcha" type="text" class="form-control" ="Write the characters in the picture">
```

**Comment by gidlov** [comment]
The "bug" has to do with Parsedown Extra-class. More specifically, the row numbers 506 and 509 in the current version.

You can probably solve it in many ways, one is to replace the word "placeholder" (at 506 and 509) to whatever you want.

Or replace Parsedown with a better alternative, michelf/php-markdown. :)

Thanks for the information darkbluesun!

**Comment by christheyounger** [comment]
Well I'm not going to go screwing around with the parsedown code because
that'll get replaced every update. Your plugin claims to work with pico
which uses parsedown by default. is there no way to escape the HTML code to
not be replaced?
