### ISSUE TITLE
updating compozer

### ISSUE THREAD

**Issue by JazzMaster** [gidlov/pico-contact#4]
and we do this HOW if we cant build it in? PHAR is not installed under dreamhost, and I cannot become root.

yet composer is a part of pico download. And note that people having issue with anchorCMS run into this too.

I can change the json file. How do I reload it?

**Comment by mats852** [comment]
Most simple solution is to work on your local machine. A VM for each site is very good, but simply running an AMP stack does the job.

Develop locally, and then upload your files when you need to update your site.
